CREATE TABLE IF NOT EXISTS emission_data (
    id SERIAL PRIMARY KEY,
    area TEXT,
    year INTEGER,
    savanna_fires FLOAT,
    forest_fires FLOAT,
    crop_residues FLOAT,
    rice_cultivation FLOAT,
    drained_soils FLOAT,
    pesticides FLOAT,
    food_transport FLOAT,
    forestland FLOAT,
    net_forest_conversion FLOAT,
    food_household FLOAT,
    food_retail FLOAT,
    onfarm_electricity FLOAT,
    food_packaging FLOAT,
    agrifood_waste FLOAT,
    food_processing FLOAT,
    fertilizers FLOAT,
    ippu FLOAT,
    manure_applied FLOAT,
    manure_left FLOAT,
    manure_management FLOAT,
    fires_organic FLOAT,
    fires_humid FLOAT,
    onfarm_energy FLOAT,
    rural_population FLOAT,
    urban_population FLOAT,
    total_pop_male FLOAT,
    total_pop_female FLOAT,
    total_emission FLOAT,
    avg_temp FLOAT
);
